import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import vercel from '../public/vercel.svg';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1>Hello World</h1>

			<Image src={vercel} width={500} height={300} alt='vercel' />
		</div>
	);
};

export default Home;
